# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projects/video_processing/src/ip/OV7670_decoder_1.4/ov7670_decoder_v1.4_project/OV7670_decoder_v1.4_project.srcs/sources_1/ip/v_vid_in_axi4s_1/v_vid_in_axi4s_1.xci
# IP: The module: 'v_vid_in_axi4s_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/video_processing/src/ip/OV7670_decoder_1.4/ov7670_decoder_v1.4_project/OV7670_decoder_v1.4_project.gen/sources_1/ip/v_vid_in_axi4s_1/v_vid_in_axi4s_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/video_processing/src/ip/OV7670_decoder_1.4/ov7670_decoder_v1.4_project/OV7670_decoder_v1.4_project.gen/sources_1/ip/v_vid_in_axi4s_1/v_vid_in_axi4s_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/projects/video_processing/src/ip/OV7670_decoder_1.4/ov7670_decoder_v1.4_project/OV7670_decoder_v1.4_project.srcs/sources_1/ip/v_vid_in_axi4s_1/v_vid_in_axi4s_1.xci
# IP: The module: 'v_vid_in_axi4s_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/video_processing/src/ip/OV7670_decoder_1.4/ov7670_decoder_v1.4_project/OV7670_decoder_v1.4_project.gen/sources_1/ip/v_vid_in_axi4s_1/v_vid_in_axi4s_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/projects/video_processing/src/ip/OV7670_decoder_1.4/ov7670_decoder_v1.4_project/OV7670_decoder_v1.4_project.gen/sources_1/ip/v_vid_in_axi4s_1/v_vid_in_axi4s_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
